### ISSUE TITLE
Cypress.currentTest.retries(2); - re-run all steps of Scenario

### ISSUE THREAD

**Issue by id-dan** [Bkucera/cypress-plugin-retries#26] opened 2019-10-10 17:10 UTC
I use [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor)

and added `Cypress.currentTest.retries(2);` to `Then` and I thought `currentTest.retries()`  re-run only `Then` instead of `Scenario` 

![image](https://user-images.githubusercontent.com/52101871/66590140-c1c54c80-eb98-11e9-91cc-a05bd90f9bb3.png)

![image](https://user-images.githubusercontent.com/52101871/66592568-fab3f000-eb9d-11e9-9d01-8fbef70ef9bc.png)

**Comment by Bkucera** [comment] 2019-10-10 19:09
@id-dan as explained in the readme, this plugin retries the entire test. It appears a test is equivalent to a scenario in cucumber 

I'm closing since this is expected behavior, but feel free to comment below

**Closed by Bkucera** 2019-10-10 19:09 UTC
