### ISSUE TITLE
Retry doesn't help with Cypress timeout error.

### ISSUE THREAD

**Issue by Lian-LF** [Bkucera/cypress-plugin-retries#6] opened 2019-03-06 17:57 UTC
Cypress sometimes throws the error for no reason:
![image](https://user-images.githubusercontent.com/20455765/53902615-80236080-400f-11e9-88d9-660c347e0f3d.png)

While the page is actually loaded.
I thought the retry plugin will address that issue. But when it retries, same thing still throws after 60s.
Are we able to refresh the page when it retries?

**Comment by Bkucera** [comment] 2019-03-07 21:51
@Lian-LF I suspect you are doing `cy.visit` inside a `beforeAll/before`, not in the test or a `beforeEach`? 

Retries will not run a `beforeAll` again because we want to guarantee `beforeAll` will only be run once.

Is this the case?

**Comment by Lian-LF** [comment] 2019-03-08 14:19
@Bkucera ehh..no, the `cy.visit` is inside test, and I did not use `beforeEach` at all.
![image](https://user-images.githubusercontent.com/20455765/54033817-512dfb80-4183-11e9-96c8-2d518652b1dd.png)

**Comment by Bkucera** [comment] 2019-03-08 18:37
@Lian-LF I see, I thought you were saying the `cy.visit` was not getting ran on retry. 

To clarify, the `cy.visit` gets ran again, but fails in the same way as before?

Do you have a reproducible example or a video of the test run?

**Comment by Lian-LF** [comment] 2019-03-08 19:22
@Bkucera  yes, the `cy.visit` ran again but fails in the same way. And I mailed the video to hello@cypress.io. Thx.

**Comment by Bkucera** [comment] 2019-03-08 19:41
I saw the video. It seems your application is either not firing the load event, or cypress is missing it for some reason.

I see no reason why this would be an issue with this plugin, so I'm going to close this.

Feel free to open an issue in the main repo if you think this is a Cypress bug.

**Closed by Bkucera** 2019-03-08 19:41 UTC
Labels: question

**Comment by lukeapage** [comment] 2019-03-24 20:00
Is the video showing the load event failing 3x (if that is the retry number) or is the plugin not retrying when visit times out?

**Comment by Bkucera** [comment] 2019-04-29 22:44
@lukeapage  the video shows the visit command failing 3 times
